name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: install and npm run grade
      id: install-and-npm-run-grade
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: install and npm run grade
        setup-command: npm install
        command: npm run grade
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INSTALL-AND-NPM-RUN-GRADE_RESULTS: "${{steps.install-and-npm-run-grade.outputs.result}}"
      with:
        runners: install-and-npm-run-grade
